### ISSUE TITLE
Orphaned Term Relationship are not deleted

### ISSUE THREAD

**Issue by slaFFik** [lesterchan/wp-sweep#1]
At all. Doing something quite long.

Than shows this messages: `8 Orphaned Term Relationships Processed`
Although in a table I see this: `Orphaned Term Relationship - 8003`

Initially posted here: https://wordpress.org/support/topic/orphaned-term-relationship-are-not-deleted?replies=1

**Comment by lesterchan** [comment]
Let's discuss it over here. It works fine on my host but I only tested on one site since I don't have access to it

It takes a long time for huge sites because it does a sub query. If you click Sweep a couple of times, does it process the remaining one or it is stuck at 8003?

Can you run this query and tell me the output?
```sql
SELECT tr.object_id, tr.term_taxonomy_id, tt.taxonomy FROM$wp_term_relationships AS tr INNER JOIN wp_term_taxonomy AS tt ON tr.term_taxonomy_id = tt.term_taxonomy_id WHERE tt.taxonomy != 'link_category' AND tr.object_id NOT IN (SELECT ID FROM wp_posts) LIMIT 100;
```

**Comment by slaFFik** [comment]
It sticks to that number.
Here is the output: http://pastebin.com/MNPdS6i3

**Comment by lesterchan** [comment]
Cool, thanks. I can reproduce it with the data. I will fix it tomorrow and update here again.

**Comment by lesterchan** [comment]
@slaFFik fixed, can you try download the zip file https://github.com/lesterchan/wp-sweep/archive/master.zip and replace wp-sweep.php to the plugin folder to see if it works now before I release 1.0.2 to the public?

**Comment by slaFFik** [comment]
Tested. Works fine.
