### ISSUE TITLE
Sweep notifications UX improvements

### ISSUE THREAD

**Issue by SiamKreative** [lesterchan/wp-sweep#13]
Currently, I think the UX can be confusing. In my opinion, the main issue is related to the WordPress notices. For one "section" (for instance Comment Sweep), multiple notices don't stack. Instead, the latest notice overwrite the previous one.

Therefore, users can easily miss bits of information. For instance, my screen shows "2 Auto Drafts Processed", while there was also "3 Revisions Processed".

## A few possible improvements

* Move the Sweep All button to the top. Users should have to scroll all the way to do this. I'm pretty sure most users will end up using "Sweep All" only.
* When users click on Sweep All, show all notices at the top (instead of being on top of every section). Because currently, users has to scroll to see what happened.

## A quick example
![image](https://cloud.githubusercontent.com/assets/1778633/6612360/a8a7f1ac-c8ad-11e4-986e-0806d2e05409.png)

Lemme know what you think...

**Comment by lesterchan** [comment]
Hmm, I prefer the Sweep All to be bottom because I want user to know what are they sweeping. I agree on the notifications can be combined when user use a sweep all.

The multiple notifications don't stack on purpose to avoid unnecessary confusing per sweep. Imagine I got like "2 Auto Drafts Process", "1 Auto Drafts Processed" It is even more confusing.
